<?php


namespace App\Tests\Functional;


use PHPUnit\Framework\TestCase;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class FunctionalTest extends WebTestCase
{
    private $client;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    public function testGetOrders()
    {
        $this->client = static::createClient();
        $this->testGetOrdersRequest();
        $this->testGetOrdersRequest( ['paramName' => 232]);
        $this->testGetOrdersRequest(['status' => 'ORDER_RECEIVED']);
        $this->testGetOrdersRequest(['status' => 'ORDER_RECEIVED']);
        $this->testGetOrdersRequest(['page' => null]);
    }
    private function testGetOrdersRequest(array $parameters = [])
    {
        $this->client->request('GET', '/api/rest/shipping-orders', $parameters);
        $this->assertResponseStatusCodeSame(200, $this->client->getResponse()->getStatusCode());
        $payLoad = json_decode($this->client->getResponse()->getContent(), true);
        //$this->assertIsArray($payLoad);
        $this->assertArrayHasKey('success', $payLoad);
        $this->assertEquals($payLoad['success'], true);
    }


    public function testGetLogs()
    {
        $this->client = static::createClient();
        $this->testGetLogsRequest('bolola' , 404, false);
        $this->testGetLogsRequest('189879898', 404, false);
        //You need to added in the database to pass the test
        //$this->testGetLogsRequest('1',  200,  true);
    }
    private function testGetLogsRequest($id, $statusCode, $success)
    {
        $this->client->request('GET', '/api/rest/log/shipping-orders/'.$id);
        $this->assertResponseStatusCodeSame($statusCode, $this->client->getResponse()->getStatusCode());
        $payLoad = json_decode($this->client->getResponse()->getContent(), true);
        $this->assertArrayHasKey('success', $payLoad);
        $this->assertEquals($payLoad['success'], $success);
    }
}